name: 'Encryption Rotation Tool'
on:
  push:
    branches:
      - main
      - v3
      - pmm-*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

  pull_request:
    paths-ignore:
      - "admin/**"
      - "agent/**"
      - "api-tests/**"
      - "cli-tests/**"
      - "docs/**"
      - "managed/**"
      - "qan-api2/**"
      - "update/**"
      - "vmproxy/**"
      - "ui/**"

jobs:
  test:
    name: Encryption Rotation Test
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    defaults:
      run:
        working-directory: ${{ github.workspace }}/encryption-rotation

    continue-on-error: true

    env:
      PMM_SERVER_IMAGE: perconalab/pmm-server:3-dev-latest
      PMM_ENCRYPTION_KEY_PATH: pmm-encryption.key

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go release
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.workspace }}/go.mod
          cache: false

      - name: Enable Go build cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ github.ref }}-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ github.ref }}-
            ${{ runner.os }}-go-build-

      - name: Enable Go modules cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-modules-

      - name: Download Go modules
        run: go mod download -x

      - name: Launch containers
        env:
          ENV_UP_FLAGS: "--detach"
        run: make env-up

      - name: Run tests
        run: make test

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          echo "--- Environment variables ---"
          env | sort
          echo "--- GO Environment ---"
          go env | sort
          git status

